name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to docker-hub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build docker-image
      run: docker build -t galinko/todolist-flask:latest .
    
    - name: Tag docker-image
      run: docker tag $(docker images -aq | head -n1) ${{ secrets.DOCKER_USERNAME }}/todolist-flask:latest
      
    - name: Push to registry
      run: docker push ${{ secrets.DOCKER_USERNAME }}/todolist-flask:latest

    
